### ISSUE TITLE
collisions?

### ISSUE THREAD

**Issue by knasim** [Constantine-32/Sha256#1]
any concerns of collisions ?

**Comment by christian-callau** [comment]
This is merely an implementation, I'm no expert in SHA-2 so I reccomend you to search about this toppic somewhere else. You should take a look at the [birthday paradox](http://en.wikipedia.org/wiki/Birthday_paradox). If you want a short answer, the probability of collision is so small that you shouldn't even think about it.

**Comment by knasim** [comment]
sure thanks.
